### ISSUE TITLE
Gets no data on any keyword

### ISSUE THREAD

**Issue by e-orlov** [wassname/keywordshitter2#8]
Tested it with Chrome and Firefox - no data in simple and advanced mode and with any keyword. Look at [screenshot with iphone as basis keyword](http://easycaptures.com/5668217084)

**Comment by wassname** [comment]
Same for me. The js error says that results must be served in https. So I made the requests to be the same protocol as the parent page. It now works for me.

**Comment by wassname** [comment]
Thanks for reporting that by the way, let me know if it doesn't work for you now.
